# Generated by Django 3.0 on 2021-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createartist',
            name='profileimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
