# Generated by Django 3.0 on 2021-02-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210216_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createartist',
            name='profileimg',
        ),
    ]
