# Generated by Django 3.0 on 2021-02-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testcreate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcreate',
            name='image',
        ),
    ]
