# Generated by Django 3.0 on 2021-02-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_testcreate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcreate',
            name='image',
            field=models.ImageField(default='hii', upload_to='images/'),
            preserve_default=False,
        ),
    ]
