# Generated by Django 3.0 on 2021-02-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testcreate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcreate',
            old_name='image',
            new_name='images',
        ),
    ]
