# Generated by Django 3.0 on 2021-02-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_testcreate_cold'),
    ]

    operations = [
        migrations.AddField(
            model_name='createartist',
            name='profileimg',
            field=models.ImageField(default='d', upload_to='image/'),
            preserve_default=False,
        ),
    ]
