# Generated by Django 3.0 on 2021-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_createartist_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='createartist',
            name='emailid',
            field=models.EmailField(default='sure', max_length=30),
            preserve_default=False,
        ),
    ]
